INSERT INTO AUTHORS (AUTHOR_ID, NAME, GENDER, BIRTHDAY) VALUES (1, 'Cay S. Horstmann', 'MALE', '1959-06-16');
INSERT INTO AUTHORS (AUTHOR_ID, NAME, GENDER, BIRTHDAY) VALUES (2, 'Joshua Bloch', 'MALE', '1961-08-28');
