INSERT INTO AUTHORS (AUTHOR_ID, NAME, GENDER, BIRTHDATE) 
VALUES (1, 'Cay S. Horstmann', 'MALE', '1959-06-16');

INSERT INTO AUTHORS (AUTHOR_ID, NAME, GENDER, BIRTHDATE) 
VALUES (2, 'Joshua Bloch', 'MALE', '1961-08-28');

INSERT INTO AUTHORS (AUTHOR_ID, NAME, GENDER, BIRTHDATE) 
VALUES (3, 'Herbert Schildt', 'MALE', '1951-02-28');

INSERT INTO AUTHORS (AUTHOR_ID, NAME, GENDER, BIRTHDATE) 
VALUES (4, 'Robert Cecil Martin', 'MALE', '1952-12-05');
